//! OpenAPI 3 specification root for the OpenFang daemon HTTP API.
//!
//! Every annotated handler in `routes.rs`, `files_browser.rs`, and `openai_compat.rs`
//! is registered here. The spec is emitted by `cargo xtask openapi` and consumed
//! by the Vite/shadcn client via `openapi-typescript`.

use serde::Serialize;
use utoipa::OpenApi;

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct HealthResponse {
    pub status: String,
    pub version: String,
}

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct ModelRef {
    pub provider: String,
    pub model: String,
}

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct AgentSummary {
    pub id: String,
    pub name: String,
    pub state: String,
    pub model: ModelRef,
    pub generating: bool,
}

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct KillResponse {
    pub status: String,
    pub agent_id: String,
}

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct SessionsListResponse {
    #[schema(value_type = Vec<Object>)]
    pub sessions: Vec<serde_json::Value>,
}

#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct SkillSummary {
    pub name: String,
    pub description: String,
    #[serde(default)]
    pub version: Option<String>,
    pub source: String,
}

#[derive(OpenApi)]
#[openapi(
    info(
        title = "OpenFang Daemon API",
        version = env!("CARGO_PKG_VERSION"),
        description = "REST API for the OpenFang Agent Operating System daemon."
    ),
    paths(
        crate::files_browser::download_file,
        crate::files_browser::list_dir,
        crate::files_browser::list_roots,
        crate::files_browser::read_file,
        crate::openai_compat::chat_completions,
        crate::openai_compat::list_models,
        crate::routes::a2a_agent_card,
        crate::routes::a2a_cancel_task,
        crate::routes::a2a_discover_external,
        crate::routes::a2a_external_task_status,
        crate::routes::a2a_get_artifact,
        crate::routes::a2a_get_task,
        crate::routes::a2a_list_agents,
        crate::routes::a2a_list_external_agents,
        crate::routes::a2a_send_external,
        crate::routes::a2a_send_task,
        crate::routes::a2a_send_task_subscribe,
        crate::routes::activate_hand,
        crate::routes::add_binding,
        crate::routes::add_custom_model,
        crate::routes::add_integration,
        crate::routes::agent_budget_ranking,
        crate::routes::agent_budget_status,
        crate::routes::approve_request,
        crate::routes::audit_recent,
        crate::routes::audit_verify,
        crate::routes::auth_check,
        crate::routes::auth_login,
        crate::routes::auth_logout,
        crate::routes::budget_status,
        crate::routes::check_hand_deps,
        crate::routes::clawhub_browse,
        crate::routes::clawhub_install,
        crate::routes::clawhub_search,
        crate::routes::clawhub_skill_code,
        crate::routes::clawhub_skill_detail,
        crate::routes::clear_agent_history,
        crate::routes::clone_agent,
        crate::routes::comms_events,
        crate::routes::comms_events_stream,
        crate::routes::comms_send,
        crate::routes::comms_task,
        crate::routes::comms_topology,
        crate::routes::compact_session,
        crate::routes::config_reload,
        crate::routes::config_schema,
        crate::routes::config_set,
        crate::routes::configure_channel,
        crate::routes::copilot_oauth_poll,
        crate::routes::copilot_oauth_start,
        crate::routes::create_agent_session,
        crate::routes::create_approval,
        crate::routes::create_cron_job,
        crate::routes::create_schedule,
        crate::routes::create_skill,
        crate::routes::create_trigger,
        crate::routes::create_workflow,
        crate::routes::cron_job_status,
        crate::routes::deactivate_hand,
        crate::routes::delete_agent_kv_key,
        crate::routes::delete_cron_job,
        crate::routes::delete_provider_key,
        crate::routes::delete_schedule,
        crate::routes::delete_session,
        crate::routes::delete_skill_config_var,
        crate::routes::delete_trigger,
        crate::routes::delete_workflow,
        crate::routes::evolve_analyze_session,
        crate::routes::evolve_batch_apply_cancel,
        crate::routes::evolve_batch_apply_preview,
        crate::routes::evolve_batch_apply_run,
        crate::routes::evolve_batch_apply_status,
        crate::routes::evolve_cost,
        crate::routes::evolve_delete_skill,
        crate::routes::evolve_delete_suggestion,
        crate::routes::evolve_execute,
        crate::routes::evolve_execute_all,
        crate::routes::evolve_execute_status,
        crate::routes::evolve_execute_stream,
        crate::routes::evolve_get_agent,
        crate::routes::evolve_get_analysis,
        crate::routes::evolve_get_config,
        crate::routes::evolve_get_skill,
        crate::routes::evolve_list_analyses,
        crate::routes::evolve_list_skills,
        crate::routes::evolve_rollback_skill,
        crate::routes::evolve_run,
        crate::routes::evolve_run_status,
        crate::routes::evolve_run_stream,
        crate::routes::evolve_set_config,
        crate::routes::evolve_stats,
        crate::routes::evolve_trigger_metrics,
        crate::routes::find_session_by_label,
        crate::routes::get_agent,
        crate::routes::get_agent_context,
        crate::routes::get_agent_deliveries,
        crate::routes::get_agent_file,
        crate::routes::get_agent_kv,
        crate::routes::get_agent_kv_key,
        crate::routes::get_agent_mcp_servers,
        crate::routes::get_agent_session,
        crate::routes::get_agent_skills,
        crate::routes::get_agent_taint_policy,
        crate::routes::get_agent_tools,
        crate::routes::get_config,
        crate::routes::get_hand,
        crate::routes::get_hand_settings,
        crate::routes::get_model,
        crate::routes::get_skill_config,
        crate::routes::get_skill_detail,
        crate::routes::get_skill_file,
        crate::routes::get_template,
        crate::routes::get_workflow,
        crate::routes::hand_instance_browser,
        crate::routes::hand_stats,
        crate::routes::health,
        crate::routes::health_detail,
        crate::routes::install_hand,
        crate::routes::install_hand_deps,
        crate::routes::install_skill,
        crate::routes::integrations_health,
        crate::routes::kill_agent,
        crate::routes::list_active_hands,
        crate::routes::list_agent_files,
        crate::routes::list_agent_sessions,
        crate::routes::list_agents,
        crate::routes::list_aliases,
        crate::routes::list_approvals,
        crate::routes::list_available_integrations,
        crate::routes::list_bindings,
        crate::routes::list_channels,
        crate::routes::list_commands,
        crate::routes::list_cron_jobs,
        crate::routes::list_hands,
        crate::routes::list_integrations,
        crate::routes::list_mcp_servers,
        crate::routes::list_models,
        crate::routes::list_peers,
        crate::routes::list_profiles,
        crate::routes::list_providers,
        crate::routes::list_schedules,
        crate::routes::list_sessions,
        crate::routes::list_skills,
        crate::routes::list_templates,
        crate::routes::list_tools,
        crate::routes::list_triggers,
        crate::routes::list_workflow_runs,
        crate::routes::list_workflows,
        crate::routes::logs_stream,
        crate::routes::marketplace_search,
        crate::routes::mcp_http,
        crate::routes::migrate_detect,
        crate::routes::migrate_scan,
        crate::routes::network_status,
        crate::routes::pairing_complete,
        crate::routes::pairing_devices,
        crate::routes::pairing_notify,
        crate::routes::pairing_remove_device,
        crate::routes::pairing_request,
        crate::routes::patch_agent,
        crate::routes::patch_agent_config,
        crate::routes::pause_hand,
        crate::routes::prometheus_metrics,
        crate::routes::put_skill_config,
        crate::routes::reconnect_integration,
        crate::routes::reject_request,
        crate::routes::reload_channels,
        crate::routes::reload_integrations,
        crate::routes::reload_skills,
        crate::routes::remove_binding,
        crate::routes::remove_channel,
        crate::routes::remove_custom_model,
        crate::routes::remove_integration,
        crate::routes::reset_session,
        crate::routes::restart_agent,
        crate::routes::resume_hand,
        crate::routes::run_cron_job,
        crate::routes::run_migrate,
        crate::routes::run_schedule,
        crate::routes::run_workflow,
        crate::routes::schedule_delivery_log,
        crate::routes::security_status,
        crate::routes::send_message,
        crate::routes::send_message_stream,
        crate::routes::serve_upload,
        crate::routes::set_agent_file,
        crate::routes::set_agent_kv_key,
        crate::routes::set_agent_mcp_servers,
        crate::routes::set_agent_mode,
        crate::routes::set_agent_skills,
        crate::routes::set_agent_taint_policy,
        crate::routes::set_agent_tools,
        crate::routes::set_hand_autonomous_tick,
        crate::routes::set_model,
        crate::routes::set_provider_key,
        crate::routes::set_provider_url,
        crate::routes::set_session_label,
        crate::routes::shutdown,
        crate::routes::spawn_agent,
        crate::routes::status,
        crate::routes::stop_agent,
        crate::routes::switch_agent_session,
        crate::routes::test_channel,
        crate::routes::test_provider,
        crate::routes::toggle_cron_job,
        crate::routes::uninstall_skill,
        crate::routes::update_agent,
        crate::routes::update_agent_budget,
        crate::routes::update_agent_identity,
        crate::routes::update_budget,
        crate::routes::update_hand_settings,
        crate::routes::update_model,
        crate::routes::update_schedule,
        crate::routes::update_trigger,
        crate::routes::update_workflow,
        crate::routes::upload_file,
        crate::routes::upsert_hand,
        crate::routes::usage_by_model,
        crate::routes::usage_daily,
        crate::routes::usage_stats,
        crate::routes::usage_summary,
        crate::routes::version,
        crate::routes::webhook_agent,
        crate::routes::webhook_wake,
        crate::routes::whatsapp_qr_start,
        crate::routes::whatsapp_qr_status,
        crate::routes::wizard_plan,
        crate::routes::wizard_spawn,
    ),
    components(schemas(
        HealthResponse,
        ModelRef,
        AgentSummary,
        KillResponse,
        SessionsListResponse,
        SkillSummary,
        crate::types::SpawnRequest,
        crate::types::SpawnResponse,
        crate::types::MessageRequest,
        crate::types::MessageResponse,
        crate::types::AttachmentRef,
        crate::types::SkillInstallRequest,
        crate::types::SkillUninstallRequest,
        crate::types::AgentUpdateRequest,
        crate::types::SetModeRequest,
        crate::types::MigrateRequest,
        crate::types::MigrateScanRequest,
        crate::types::ClawHubInstallRequest,
        crate::types::CommandsQuery,
        openfang_types::model_catalog::ProviderInfo,
    )),
    tags(
        (name = "system",         description = "Health, version, status, config, metrics"),
        (name = "agents",         description = "Agent lifecycle, messaging, configuration"),
        (name = "sessions",       description = "Conversation sessions"),
        (name = "skills",         description = "Skill catalog, install, ClawHub, marketplace"),
        (name = "providers",      description = "LLM provider configuration"),
        (name = "channels",       description = "External communication channels"),
        (name = "comms",          description = "Inter-agent communication"),
        (name = "hands",          description = "Browser automation hands"),
        (name = "automation",     description = "Triggers, schedules, cron jobs"),
        (name = "workflows",      description = "Workflow orchestration"),
        (name = "memory",         description = "Agent KV store"),
        (name = "files",          description = "File browser and uploads"),
        (name = "evolve",         description = "Evolution analyzer + suggestion pipeline"),
        (name = "budget",         description = "Cost tracking and budget"),
        (name = "audit",          description = "Audit log and live logs"),
        (name = "approvals",      description = "Human-in-the-loop approvals"),
        (name = "network",        description = "OFP peer network"),
        (name = "a2a",            description = "Agent-to-Agent protocol"),
        (name = "integrations",   description = "Third-party integrations"),
        (name = "pairing",        description = "Device pairing"),
        (name = "auth",           description = "Dashboard session auth"),
        (name = "migrate",        description = "Data migration from other agent frameworks"),
        (name = "tools",          description = "Tool catalog"),
        (name = "mcp",            description = "MCP servers + HTTP transport"),
        (name = "openai-compat",  description = "OpenAI-compatible /v1 endpoints"),
        (name = "webhooks",       description = "External event injection"),
        (name = "bindings",       description = "Channel-to-agent bindings"),
    ),
)]
pub struct ApiDoc;
